import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const languages = {
  en: { name: 'English', flag: '🇺🇸', nativeName: 'English' },
  es: { name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  fr: { name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  de: { name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  it: { name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  pt: { name: 'Portuguese', flag: '🇵🇹', nativeName: 'Português' },
  ru: { name: 'Russian', flag: '🇷🇺', nativeName: 'Русский' },
  zh: { name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  ja: { name: 'Japanese', flag: '🇯🇵', nativeName: '日本語' },
  ko: { name: 'Korean', flag: '🇰🇷', nativeName: '한국어' },
  ar: { name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية' },
  hi: { name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  nl: { name: 'Dutch', flag: '🇳🇱', nativeName: 'Nederlands' },
  sv: { name: 'Swedish', flag: '🇸🇪', nativeName: 'Svenska' },
  no: { name: 'Norwegian', flag: '🇳🇴', nativeName: 'Norsk' },
  da: { name: 'Danish', flag: '🇩🇰', nativeName: 'Dansk' },
  fi: { name: 'Finnish', flag: '🇫🇮', nativeName: 'Suomi' },
  pl: { name: 'Polish', flag: '🇵🇱', nativeName: 'Polski' },
  tr: { name: 'Turkish', flag: '🇹🇷', nativeName: 'Türkçe' },
  th: { name: 'Thai', flag: '🇹🇭', nativeName: 'ไทย' },
  vi: { name: 'Vietnamese', flag: '🇻🇳', nativeName: 'Tiếng Việt' },
  id: { name: 'Indonesian', flag: '🇮🇩', nativeName: 'Bahasa Indonesia' },
  ms: { name: 'Malay', flag: '🇲🇾', nativeName: 'Bahasa Melayu' },
  he: { name: 'Hebrew', flag: '🇮🇱', nativeName: 'עברית' },
  uk: { name: 'Ukrainian', flag: '🇺🇦', nativeName: 'Українська' },
  cs: { name: 'Czech', flag: '🇨🇿', nativeName: 'Čeština' },
  sk: { name: 'Slovak', flag: '🇸🇰', nativeName: 'Slovenčina' },
  hu: { name: 'Hungarian', flag: '🇭🇺', nativeName: 'Magyar' },
  ro: { name: 'Romanian', flag: '🇷🇴', nativeName: 'Română' },
  bg: { name: 'Bulgarian', flag: '🇧🇬', nativeName: 'Български' },
  hr: { name: 'Croatian', flag: '🇭🇷', nativeName: 'Hrvatski' },
  sr: { name: 'Serbian', flag: '🇷🇸', nativeName: 'Српски' },
  sl: { name: 'Slovenian', flag: '🇸🇮', nativeName: 'Slovenščina' },
  et: { name: 'Estonian', flag: '🇪🇪', nativeName: 'Eesti' },
  lv: { name: 'Latvian', flag: '🇱🇻', nativeName: 'Latviešu' },
  lt: { name: 'Lithuanian', flag: '🇱🇹', nativeName: 'Lietuvių' },
  el: { name: 'Greek', flag: '🇬🇷', nativeName: 'Ελληνικά' },
  ca: { name: 'Catalan', flag: '🇪🇸', nativeName: 'Català' },
  eu: { name: 'Basque', flag: '🇪🇸', nativeName: 'Euskera' },
  ga: { name: 'Irish', flag: '🇮🇪', nativeName: 'Gaeilge' },
  cy: { name: 'Welsh', flag: '🇬🇧', nativeName: 'Cymraeg' },
  mt: { name: 'Maltese', flag: '🇲🇹', nativeName: 'Malti' },
  is: { name: 'Icelandic', flag: '🇮🇸', nativeName: 'Íslenska' },
  fa: { name: 'Persian', flag: '🇮🇷', nativeName: 'فارسی' },
  ur: { name: 'Urdu', flag: '🇵🇰', nativeName: 'اردو' },
  bn: { name: 'Bengali', flag: '🇧🇩', nativeName: 'বাংলা' },
  ta: { name: 'Tamil', flag: '🇮🇳', nativeName: 'தமிழ்' },
  te: { name: 'Telugu', flag: '🇮🇳', nativeName: 'తెలుగు' },
  ml: { name: 'Malayalam', flag: '🇮🇳', nativeName: 'മലയാളം' },
  kn: { name: 'Kannada', flag: '🇮🇳', nativeName: 'ಕನ್ನಡ' },
  gu: { name: 'Gujarati', flag: '🇮🇳', nativeName: 'ગુજરાતી' },
  pa: { name: 'Punjabi', flag: '🇮🇳', nativeName: 'ਪੰਜਾਬੀ' },
  mr: { name: 'Marathi', flag: '🇮🇳', nativeName: 'मराठी' },
  or: { name: 'Odia', flag: '🇮🇳', nativeName: 'ଓଡ଼ିଆ' },
  as: { name: 'Assamese', flag: '🇮🇳', nativeName: 'অসমীয়া' },
  ne: { name: 'Nepali', flag: '🇳🇵', nativeName: 'नेपाली' },
  si: { name: 'Sinhala', flag: '🇱🇰', nativeName: 'සිංහල' },
  my: { name: 'Burmese', flag: '🇲🇲', nativeName: 'မြန်မာ' },
  km: { name: 'Khmer', flag: '🇰🇭', nativeName: 'ខ្មែរ' },
  lo: { name: 'Lao', flag: '🇱🇦', nativeName: 'ລາວ' },
  ka: { name: 'Georgian', flag: '🇬🇪', nativeName: 'ქართული' },
  hy: { name: 'Armenian', flag: '🇦🇲', nativeName: 'Հայերեն' },
  az: { name: 'Azerbaijani', flag: '🇦🇿', nativeName: 'Azərbaycan' },
  kk: { name: 'Kazakh', flag: '🇰🇿', nativeName: 'Қазақша' },
  ky: { name: 'Kyrgyz', flag: '🇰🇬', nativeName: 'Кыргызча' },
  uz: { name: 'Uzbek', flag: '🇺🇿', nativeName: 'Oʻzbekcha' },
  tg: { name: 'Tajik', flag: '🇹🇯', nativeName: 'Тоҷикӣ' },
  mn: { name: 'Mongolian', flag: '🇲🇳', nativeName: 'Монгол' },
  bo: { name: 'Tibetan', flag: '🇨🇳', nativeName: 'བོད་ཡིག' },
  ug: { name: 'Uyghur', flag: '🇨🇳', nativeName: 'ئۇيغۇرچە' },
  sw: { name: 'Swahili', flag: '🇰🇪', nativeName: 'Kiswahili' },
  am: { name: 'Amharic', flag: '🇪🇹', nativeName: 'አማርኛ' },
  ha: { name: 'Hausa', flag: '🇳🇬', nativeName: 'Hausa' },
  yo: { name: 'Yoruba', flag: '🇳🇬', nativeName: 'Yorùbá' },
  ig: { name: 'Igbo', flag: '🇳🇬', nativeName: 'Igbo' },
  zu: { name: 'Zulu', flag: '🇿🇦', nativeName: 'IsiZulu' },
  xh: { name: 'Xhosa', flag: '🇿🇦', nativeName: 'IsiXhosa' },
  af: { name: 'Afrikaans', flag: '🇿🇦', nativeName: 'Afrikaans' },
  sq: { name: 'Albanian', flag: '🇦🇱', nativeName: 'Shqip' },
  mk: { name: 'Macedonian', flag: '🇲🇰', nativeName: 'Македонски' },
  bs: { name: 'Bosnian', flag: '🇧🇦', nativeName: 'Bosanski' },
  mk: { name: 'Montenegrin', flag: '🇲🇪', nativeName: 'Crnogorski' }
};

const translations = {
  en: {
    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    researchPapers: 'Research Papers',
    knowledgeGraph: 'Knowledge Graph',
    aiInsights: 'AI Insights',
    
    // Dashboard
    welcomeToNASA: 'Welcome to NASA BioExplorer',
    exploreFuture: 'Explore the future of space biology with AI-powered insights and interactive visualizations',
    researchPapersCount: 'Research Papers',
    researchAreasCount: 'Research Areas',
    organizationsCount: 'Organizations',
    totalPapers: 'Total Papers',
    totalAreas: 'Total Areas',
    totalOrganizations: 'Total Organizations',
    
    // Charts
    researchTimeline: 'Research Timeline',
    mostVisitedPapers: 'Most Visited Papers',
    systemStatus: 'System Status',
    weather: 'Weather',
    online: 'Online',
    offline: 'Offline',
    
    // Research Papers
    allPapers: 'All Papers',
    summary: 'Summary',
    knowledgeGraphBtn: 'Knowledge Graph',
    keywords: 'Keywords',
    openPaper: 'Open Paper',
    sortBy: 'Sort By',
    filterBy: 'Filter By',
    
    // Common
    loading: 'Loading...',
    search: 'Search',
    filter: 'Filter',
    view: 'View',
    grid: 'Grid',
    list: 'List',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    export: 'Export',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    noResults: 'No results found',
    tryAdjusting: 'Try adjusting your search or filters',
    
    // Chatbot
    chatbotWelcome: 'Hello! I\'m your NASA Space Research Assistant. I can help you with questions about space biology, research papers, missions, and more. How can I assist you today?',
    chatbotGreeting: 'Hello! I\'m here to help you explore the fascinating world of space research. What would you like to know about NASA\'s biology research or space missions?',
    chatbotResearch: 'NASA conducts extensive research in space biology, including studies on human physiology, plant growth, microbiology, and psychological factors. Would you like to know about a specific research area?',
    chatbotMission: 'NASA missions study how humans adapt to space environments. Key research areas include cardiovascular health, bone density, muscle mass, and psychological well-being during long-duration missions.',
    chatbotHealth: 'Space medicine research focuses on maintaining astronaut health in microgravity. This includes studies on bone loss, muscle atrophy, cardiovascular changes, and radiation effects.',
    chatbotFuture: 'Future missions to Mars will require extensive research on long-duration spaceflight effects, life support systems, and psychological factors. NASA is actively studying these challenges.',
    chatbotHelp: 'I can help you with information about space biology research, NASA missions, astronaut health, microgravity effects, space food, radiation, and much more! Just ask me about any space-related topic.',
    chatbotDefault: 'That\'s an interesting question about space research! While I have extensive knowledge about NASA\'s biology research, I might need more specific information. Could you tell me more about what aspect of space research you\'re interested in?',
    chatbotPlaceholder: 'Ask me about space research...',
    chatbotOnline: 'Online',
    chatbotAssistant: 'NASA Space Assistant'
  },
  es: {
    home: 'Inicio',
    dashboard: 'Panel de Control',
    researchPapers: 'Artículos de Investigación',
    knowledgeGraph: 'Grafo de Conocimiento',
    aiInsights: 'Perspectivas IA',
    welcomeToNASA: 'Bienvenido a NASA BioExplorer',
    exploreFuture: 'Explora el futuro de la biología espacial con perspectivas impulsadas por IA y visualizaciones interactivas',
    researchPapersCount: 'Artículos de Investigación',
    researchAreasCount: 'Áreas de Investigación',
    organizationsCount: 'Organizaciones',
    totalPapers: 'Total de Artículos',
    totalAreas: 'Total de Áreas',
    totalOrganizations: 'Total de Organizaciones',
    researchTimeline: 'Cronología de Investigación',
    mostVisitedPapers: 'Artículos Más Visitados',
    systemStatus: 'Estado del Sistema',
    weather: 'Clima',
    online: 'En Línea',
    offline: 'Desconectado',
    allPapers: 'Todos los Artículos',
    summary: 'Resumen',
    knowledgeGraphBtn: 'Grafo de Conocimiento',
    keywords: 'Palabras Clave',
    openPaper: 'Abrir Artículo',
    sortBy: 'Ordenar Por',
    filterBy: 'Filtrar Por',
    loading: 'Cargando...',
    search: 'Buscar',
    filter: 'Filtrar',
    view: 'Vista',
    grid: 'Cuadrícula',
    list: 'Lista',
    selectAll: 'Seleccionar Todo',
    deselectAll: 'Deseleccionar Todo',
    export: 'Exportar',
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página',
    of: 'de',
    noResults: 'No se encontraron resultados',
    tryAdjusting: 'Intenta ajustar tu búsqueda o filtros',
    
    // Chatbot
    chatbotWelcome: '¡Hola! Soy tu Asistente de Investigación Espacial de la NASA. Puedo ayudarte con preguntas sobre biología espacial, artículos de investigación, misiones y más. ¿Cómo puedo asistirte hoy?',
    chatbotGreeting: '¡Hola! Estoy aquí para ayudarte a explorar el fascinante mundo de la investigación espacial. ¿Qué te gustaría saber sobre la investigación biológica de la NASA o las misiones espaciales?',
    chatbotResearch: 'La NASA realiza extensas investigaciones en biología espacial, incluyendo estudios sobre fisiología humana, crecimiento de plantas, microbiología y factores psicológicos. ¿Te gustaría saber sobre un área de investigación específica?',
    chatbotMission: 'Las misiones de la NASA estudian cómo los humanos se adaptan a los entornos espaciales. Las áreas clave de investigación incluyen salud cardiovascular, densidad ósea, masa muscular y bienestar psicológico durante misiones de larga duración.',
    chatbotHealth: 'La investigación en medicina espacial se enfoca en mantener la salud de los astronautas en microgravedad. Esto incluye estudios sobre pérdida ósea, atrofia muscular, cambios cardiovasculares y efectos de la radiación.',
    chatbotFuture: 'Las futuras misiones a Marte requerirán extensas investigaciones sobre los efectos de vuelos espaciales de larga duración, sistemas de soporte vital y factores psicológicos. La NASA está estudiando activamente estos desafíos.',
    chatbotHelp: '¡Puedo ayudarte con información sobre investigación en biología espacial, misiones de la NASA, salud de astronautas, efectos de microgravedad, comida espacial, radiación y mucho más! Solo pregúntame sobre cualquier tema relacionado con el espacio.',
    chatbotDefault: '¡Esa es una pregunta interesante sobre investigación espacial! Aunque tengo amplio conocimiento sobre la investigación biológica de la NASA, podría necesitar información más específica. ¿Podrías contarme más sobre qué aspecto de la investigación espacial te interesa?',
    chatbotPlaceholder: 'Pregúntame sobre investigación espacial...',
    chatbotOnline: 'En Línea',
    chatbotAssistant: 'Asistente Espacial NASA'
  },
  fr: {
    home: 'Accueil',
    dashboard: 'Tableau de Bord',
    researchPapers: 'Articles de Recherche',
    knowledgeGraph: 'Graphe de Connaissance',
    aiInsights: 'Insights IA',
    welcomeToNASA: 'Bienvenue sur NASA BioExplorer',
    exploreFuture: 'Explorez l\'avenir de la biologie spatiale avec des insights alimentés par l\'IA et des visualisations interactives',
    researchPapersCount: 'Articles de Recherche',
    researchAreasCount: 'Domaines de Recherche',
    organizationsCount: 'Organisations',
    totalPapers: 'Total des Articles',
    totalAreas: 'Total des Domaines',
    totalOrganizations: 'Total des Organisations',
    researchTimeline: 'Chronologie de Recherche',
    mostVisitedPapers: 'Articles les Plus Consultés',
    systemStatus: 'État du Système',
    weather: 'Météo',
    online: 'En Ligne',
    offline: 'Hors Ligne',
    allPapers: 'Tous les Articles',
    summary: 'Résumé',
    knowledgeGraphBtn: 'Graphe de Connaissance',
    keywords: 'Mots-clés',
    openPaper: 'Ouvrir l\'Article',
    sortBy: 'Trier Par',
    filterBy: 'Filtrer Par',
    loading: 'Chargement...',
    search: 'Rechercher',
    filter: 'Filtrer',
    view: 'Vue',
    grid: 'Grille',
    list: 'Liste',
    selectAll: 'Tout Sélectionner',
    deselectAll: 'Tout Désélectionner',
    export: 'Exporter',
    previous: 'Précédent',
    next: 'Suivant',
    page: 'Page',
    of: 'de',
    noResults: 'Aucun résultat trouvé',
    tryAdjusting: 'Essayez d\'ajuster votre recherche ou vos filtres',
    
    // Chatbot
    chatbotWelcome: 'Bonjour ! Je suis votre Assistant de Recherche Spatiale de la NASA. Je peux vous aider avec des questions sur la biologie spatiale, les articles de recherche, les missions et plus encore. Comment puis-je vous aider aujourd\'hui ?',
    chatbotGreeting: 'Bonjour ! Je suis là pour vous aider à explorer le monde fascinant de la recherche spatiale. Que souhaiteriez-vous savoir sur la recherche biologique de la NASA ou les missions spatiales ?',
    chatbotResearch: 'La NASA mène des recherches approfondies en biologie spatiale, incluant des études sur la physiologie humaine, la croissance des plantes, la microbiologie et les facteurs psychologiques. Souhaiteriez-vous connaître un domaine de recherche spécifique ?',
    chatbotMission: 'Les missions de la NASA étudient comment les humains s\'adaptent aux environnements spatiaux. Les domaines clés incluent la santé cardiovasculaire, la densité osseuse, la masse musculaire et le bien-être psychologique lors de missions de longue durée.',
    chatbotHealth: 'La recherche en médecine spatiale se concentre sur le maintien de la santé des astronautes en microgravité. Cela inclut des études sur la perte osseuse, l\'atrophie musculaire, les changements cardiovasculaires et les effets des radiations.',
    chatbotFuture: 'Les futures missions vers Mars nécessiteront des recherches approfondies sur les effets des vols spatiaux de longue durée, les systèmes de support vital et les facteurs psychologiques. La NASA étudie activement ces défis.',
    chatbotHelp: 'Je peux vous aider avec des informations sur la recherche en biologie spatiale, les missions de la NASA, la santé des astronautes, les effets de la microgravité, la nourriture spatiale, les radiations et bien plus ! Demandez-moi simplement sur tout sujet lié à l\'espace.',
    chatbotDefault: 'C\'est une question intéressante sur la recherche spatiale ! Bien que j\'aie une vaste connaissance de la recherche biologique de la NASA, j\'aurais peut-être besoin d\'informations plus spécifiques. Pourriez-vous me dire plus sur quel aspect de la recherche spatiale vous intéresse ?',
    chatbotPlaceholder: 'Demandez-moi sur la recherche spatiale...',
    chatbotOnline: 'En Ligne',
    chatbotAssistant: 'Assistant Spatial NASA'
  },
  de: {
    home: 'Startseite',
    dashboard: 'Dashboard',
    researchPapers: 'Forschungsarbeiten',
    knowledgeGraph: 'Wissensgraph',
    aiInsights: 'KI-Einblicke',
    welcomeToNASA: 'Willkommen bei NASA BioExplorer',
    exploreFuture: 'Erkunden Sie die Zukunft der Weltraumbiologie mit KI-gestützten Einblicken und interaktiven Visualisierungen',
    researchPapersCount: 'Forschungsarbeiten',
    researchAreasCount: 'Forschungsbereiche',
    organizationsCount: 'Organisationen',
    totalPapers: 'Gesamtarbeiten',
    totalAreas: 'Gesamtbereiche',
    totalOrganizations: 'Gesamtorganisationen',
    researchTimeline: 'Forschungstimeline',
    mostVisitedPapers: 'Meistbesuchte Arbeiten',
    systemStatus: 'Systemstatus',
    weather: 'Wetter',
    online: 'Online',
    offline: 'Offline',
    allPapers: 'Alle Arbeiten',
    summary: 'Zusammenfassung',
    knowledgeGraphBtn: 'Wissensgraph',
    keywords: 'Schlüsselwörter',
    openPaper: 'Arbeit Öffnen',
    sortBy: 'Sortieren Nach',
    filterBy: 'Filtern Nach',
    loading: 'Laden...',
    search: 'Suchen',
    filter: 'Filter',
    view: 'Ansicht',
    grid: 'Raster',
    list: 'Liste',
    selectAll: 'Alle Auswählen',
    deselectAll: 'Alle Abwählen',
    export: 'Exportieren',
    previous: 'Zurück',
    next: 'Weiter',
    page: 'Seite',
    of: 'von',
    noResults: 'Keine Ergebnisse gefunden',
    tryAdjusting: 'Versuchen Sie, Ihre Suche oder Filter anzupassen',
    
    // Chatbot
    chatbotWelcome: 'Hallo! Ich bin Ihr NASA-Weltraumforschungsassistent. Ich kann Ihnen bei Fragen zur Weltraumbiologie, Forschungsarbeiten, Missionen und mehr helfen. Wie kann ich Ihnen heute helfen?',
    chatbotGreeting: 'Hallo! Ich bin hier, um Ihnen zu helfen, die faszinierende Welt der Weltraumforschung zu erkunden. Was möchten Sie über NASAs Biologieforschung oder Weltraummissionen wissen?',
    chatbotResearch: 'Die NASA führt umfangreiche Forschungen in der Weltraumbiologie durch, einschließlich Studien zur menschlichen Physiologie, Pflanzenwachstum, Mikrobiologie und psychologischen Faktoren. Möchten Sie etwas über einen bestimmten Forschungsbereich wissen?',
    chatbotMission: 'NASA-Missionen untersuchen, wie sich Menschen an Weltraumumgebungen anpassen. Zu den wichtigsten Forschungsbereichen gehören Herz-Kreislauf-Gesundheit, Knochendichte, Muskelmasse und psychisches Wohlbefinden während Langzeitmissionen.',
    chatbotHealth: 'Die Weltraummedizinforschung konzentriert sich auf die Erhaltung der Astronautengesundheit in der Schwerelosigkeit. Dazu gehören Studien über Knochenverlust, Muskelatrophie, Herz-Kreislauf-Veränderungen und Strahlungseffekte.',
    chatbotFuture: 'Zukünftige Mars-Missionen erfordern umfangreiche Forschungen zu Langzeit-Weltraumflugeffekten, Lebenserhaltungssystemen und psychologischen Faktoren. Die NASA untersucht diese Herausforderungen aktiv.',
    chatbotHelp: 'Ich kann Ihnen mit Informationen über Weltraumbiologieforschung, NASA-Missionen, Astronautengesundheit, Schwerelosigkeitseffekte, Weltraumessen, Strahlung und vielem mehr helfen! Fragen Sie mich einfach über jedes weltraumbezogene Thema.',
    chatbotDefault: 'Das ist eine interessante Frage zur Weltraumforschung! Obwohl ich umfangreiches Wissen über NASAs Biologieforschung habe, könnte ich spezifischere Informationen benötigen. Könnten Sie mir mehr über den Aspekt der Weltraumforschung erzählen, der Sie interessiert?',
    chatbotPlaceholder: 'Fragen Sie mich über Weltraumforschung...',
    chatbotOnline: 'Online',
    chatbotAssistant: 'NASA-Weltraumassistent'
  },
  zh: {
    home: '首页',
    dashboard: '仪表板',
    researchPapers: '研究论文',
    knowledgeGraph: '知识图谱',
    aiInsights: 'AI洞察',
    welcomeToNASA: '欢迎使用NASA BioExplorer',
    exploreFuture: '通过AI驱动的洞察和交互式可视化探索太空生物学的未来',
    researchPapersCount: '研究论文',
    researchAreasCount: '研究领域',
    organizationsCount: '组织机构',
    totalPapers: '总论文数',
    totalAreas: '总领域数',
    totalOrganizations: '总机构数',
    researchTimeline: '研究时间线',
    mostVisitedPapers: '最受欢迎论文',
    systemStatus: '系统状态',
    weather: '天气',
    online: '在线',
    offline: '离线',
    allPapers: '所有论文',
    summary: '摘要',
    knowledgeGraphBtn: '知识图谱',
    keywords: '关键词',
    openPaper: '打开论文',
    sortBy: '排序方式',
    filterBy: '筛选方式',
    loading: '加载中...',
    search: '搜索',
    filter: '筛选',
    view: '视图',
    grid: '网格',
    list: '列表',
    selectAll: '全选',
    deselectAll: '取消全选',
    export: '导出',
    previous: '上一页',
    next: '下一页',
    page: '页',
    of: '共',
    noResults: '未找到结果',
    tryAdjusting: '请尝试调整搜索或筛选条件',
    
    // Chatbot
    chatbotWelcome: '您好！我是您的NASA太空研究助手。我可以帮助您解答有关太空生物学、研究论文、任务等方面的问题。今天我能为您做些什么？',
    chatbotGreeting: '您好！我在这里帮助您探索迷人的太空研究世界。您想了解NASA的生物学研究或太空任务的哪些方面？',
    chatbotResearch: 'NASA在太空生物学方面进行广泛研究，包括人类生理学、植物生长、微生物学和心理因素的研究。您想了解特定的研究领域吗？',
    chatbotMission: 'NASA任务研究人类如何适应太空环境。关键研究领域包括心血管健康、骨密度、肌肉质量和长期任务期间的心理健康。',
    chatbotHealth: '太空医学研究专注于在微重力环境下维护宇航员健康。这包括骨丢失、肌肉萎缩、心血管变化和辐射效应的研究。',
    chatbotFuture: '未来的火星任务需要对长期太空飞行效应、生命支持系统和心理因素进行广泛研究。NASA正在积极研究这些挑战。',
    chatbotHelp: '我可以帮助您了解太空生物学研究、NASA任务、宇航员健康、微重力效应、太空食物、辐射等方面的信息！只需问我任何与太空相关的话题。',
    chatbotDefault: '这是关于太空研究的一个有趣问题！虽然我对NASA的生物学研究有广泛了解，但我可能需要更具体的信息。您能告诉我更多关于您感兴趣的太空研究方面吗？',
    chatbotPlaceholder: '问我关于太空研究的问题...',
    chatbotOnline: '在线',
    chatbotAssistant: 'NASA太空助手'
  },
  ja: {
    home: 'ホーム',
    dashboard: 'ダッシュボード',
    researchPapers: '研究論文',
    knowledgeGraph: '知識グラフ',
    aiInsights: 'AIインサイト',
    welcomeToNASA: 'NASA BioExplorerへようこそ',
    exploreFuture: 'AI駆動のインサイトとインタラクティブな可視化で宇宙生物学の未来を探求',
    researchPapersCount: '研究論文',
    researchAreasCount: '研究分野',
    organizationsCount: '組織',
    totalPapers: '総論文数',
    totalAreas: '総分野数',
    totalOrganizations: '総組織数',
    researchTimeline: '研究タイムライン',
    mostVisitedPapers: '最も訪問された論文',
    systemStatus: 'システム状態',
    weather: '天気',
    online: 'オンライン',
    offline: 'オフライン',
    allPapers: 'すべての論文',
    summary: '要約',
    knowledgeGraphBtn: '知識グラフ',
    keywords: 'キーワード',
    openPaper: '論文を開く',
    sortBy: '並び順',
    filterBy: 'フィルター',
    loading: '読み込み中...',
    search: '検索',
    filter: 'フィルター',
    view: '表示',
    grid: 'グリッド',
    list: 'リスト',
    selectAll: 'すべて選択',
    deselectAll: 'すべて解除',
    export: 'エクスポート',
    previous: '前へ',
    next: '次へ',
    page: 'ページ',
    of: '/',
    noResults: '結果が見つかりません',
    tryAdjusting: '検索条件やフィルターを調整してください'
  },
  ar: {
    home: 'الرئيسية',
    dashboard: 'لوحة التحكم',
    researchPapers: 'أوراق البحث',
    knowledgeGraph: 'رسم بياني للمعرفة',
    aiInsights: 'رؤى الذكاء الاصطناعي',
    welcomeToNASA: 'مرحباً بك في NASA BioExplorer',
    exploreFuture: 'استكشف مستقبل علم الأحياء الفضائية مع رؤى مدعومة بالذكاء الاصطناعي والتصورات التفاعلية',
    researchPapersCount: 'أوراق البحث',
    researchAreasCount: 'مجالات البحث',
    organizationsCount: 'المنظمات',
    totalPapers: 'إجمالي الأوراق',
    totalAreas: 'إجمالي المجالات',
    totalOrganizations: 'إجمالي المنظمات',
    researchTimeline: 'الجدول الزمني للبحث',
    mostVisitedPapers: 'الأوراق الأكثر زيارة',
    systemStatus: 'حالة النظام',
    weather: 'الطقس',
    online: 'متصل',
    offline: 'غير متصل',
    allPapers: 'جميع الأوراق',
    summary: 'ملخص',
    knowledgeGraphBtn: 'رسم بياني للمعرفة',
    keywords: 'الكلمات المفتاحية',
    openPaper: 'فتح الورقة',
    sortBy: 'ترتيب حسب',
    filterBy: 'تصفية حسب',
    loading: 'جاري التحميل...',
    search: 'بحث',
    filter: 'تصفية',
    view: 'عرض',
    grid: 'شبكة',
    list: 'قائمة',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    export: 'تصدير',
    previous: 'السابق',
    next: 'التالي',
    page: 'صفحة',
    of: 'من',
    noResults: 'لم يتم العثور على نتائج',
    tryAdjusting: 'حاول تعديل البحث أو المرشحات'
  },
  hi: {
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    researchPapers: 'अनुसंधान पत्र',
    knowledgeGraph: 'ज्ञान ग्राफ',
    aiInsights: 'AI अंतर्दृष्टि',
    welcomeToNASA: 'NASA BioExplorer में आपका स्वागत है',
    exploreFuture: 'AI-संचालित अंतर्दृष्टि और इंटरैक्टिव विज़ुअलाइज़ेशन के साथ अंतरिक्ष जीव विज्ञान के भविष्य का अन्वेषण करें',
    researchPapersCount: 'अनुसंधान पत्र',
    researchAreasCount: 'अनुसंधान क्षेत्र',
    organizationsCount: 'संगठन',
    totalPapers: 'कुल पत्र',
    totalAreas: 'कुल क्षेत्र',
    totalOrganizations: 'कुल संगठन',
    researchTimeline: 'अनुसंधान समयरेखा',
    mostVisitedPapers: 'सबसे अधिक देखे गए पत्र',
    systemStatus: 'सिस्टम स्थिति',
    weather: 'मौसम',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    allPapers: 'सभी पत्र',
    summary: 'सारांश',
    knowledgeGraphBtn: 'ज्ञान ग्राफ',
    keywords: 'कीवर्ड',
    openPaper: 'पत्र खोलें',
    sortBy: 'क्रमबद्ध करें',
    filterBy: 'फिल्टर करें',
    loading: 'लोड हो रहा है...',
    search: 'खोजें',
    filter: 'फिल्टर',
    view: 'दृश्य',
    grid: 'ग्रिड',
    list: 'सूची',
    selectAll: 'सभी चुनें',
    deselectAll: 'सभी अचयनित करें',
    export: 'निर्यात',
    previous: 'पिछला',
    next: 'अगला',
    page: 'पृष्ठ',
    of: 'का',
    noResults: 'कोई परिणाम नहीं मिला',
    tryAdjusting: 'अपनी खोज या फिल्टर को समायोजित करने का प्रयास करें'
  },
  cs: {
    home: 'Domů',
    dashboard: 'Řídicí panel',
    researchPapers: 'Výzkumné články',
    knowledgeGraph: 'Graf znalostí',
    aiInsights: 'AI poznatky',
    welcomeToNASA: 'Vítejte v NASA BioExplorer',
    exploreFuture: 'Prozkoumejte budoucnost vesmírné biologie s AI-poháněnými poznatky a interaktivními vizualizacemi',
    researchPapersCount: 'Výzkumné články',
    researchAreasCount: 'Výzkumné oblasti',
    organizationsCount: 'Organizace',
    totalPapers: 'Celkem článků',
    totalAreas: 'Celkem oblastí',
    totalOrganizations: 'Celkem organizací',
    researchTimeline: 'Časová osa výzkumu',
    mostVisitedPapers: 'Nejnavštěvovanější články',
    systemStatus: 'Stav systému',
    weather: 'Počasí',
    online: 'Online',
    offline: 'Offline',
    allPapers: 'Všechny články',
    summary: 'Souhrn',
    knowledgeGraphBtn: 'Graf znalostí',
    keywords: 'Klíčová slova',
    openPaper: 'Otevřít článek',
    sortBy: 'Seřadit podle',
    filterBy: 'Filtrovat podle',
    loading: 'Načítání...',
    search: 'Hledat',
    filter: 'Filtr',
    view: 'Zobrazení',
    grid: 'Mřížka',
    list: 'Seznam',
    selectAll: 'Vybrat vše',
    deselectAll: 'Zrušit výběr',
    export: 'Exportovat',
    previous: 'Předchozí',
    next: 'Další',
    page: 'Stránka',
    of: 'z',
    noResults: 'Žádné výsledky nenalezeny',
    tryAdjusting: 'Zkuste upravit vyhledávání nebo filtry'
  },
  sk: {
    home: 'Domov',
    dashboard: 'Ovládací panel',
    researchPapers: 'Výskumné články',
    knowledgeGraph: 'Graf znalostí',
    aiInsights: 'AI poznatky',
    welcomeToNASA: 'Vitajte v NASA BioExplorer',
    exploreFuture: 'Preskúmajte budúcnosť vesmírnej biológie s AI-poháňanými poznatkami a interaktívnymi vizualizáciami',
    researchPapersCount: 'Výskumné články',
    researchAreasCount: 'Výskumné oblasti',
    organizationsCount: 'Organizácie',
    totalPapers: 'Celkom článkov',
    totalAreas: 'Celkom oblastí',
    totalOrganizations: 'Celkom organizácií',
    researchTimeline: 'Časová os výskumu',
    mostVisitedPapers: 'Najnavštevovanejšie články',
    systemStatus: 'Stav systému',
    weather: 'Počasie',
    online: 'Online',
    offline: 'Offline',
    allPapers: 'Všetky články',
    summary: 'Súhrn',
    knowledgeGraphBtn: 'Graf znalostí',
    keywords: 'Kľúčové slová',
    openPaper: 'Otvoriť článok',
    sortBy: 'Zoradiť podľa',
    filterBy: 'Filtrovať podľa',
    loading: 'Načítavanie...',
    search: 'Hľadať',
    filter: 'Filter',
    view: 'Zobrazenie',
    grid: 'Mriežka',
    list: 'Zoznam',
    selectAll: 'Vybrať všetko',
    deselectAll: 'Zrušiť výber',
    export: 'Exportovať',
    previous: 'Predchádzajúci',
    next: 'Ďalší',
    page: 'Stránka',
    of: 'z',
    noResults: 'Žiadne výsledky nenájdené',
    tryAdjusting: 'Skúste upraviť vyhľadávanie alebo filtre'
  },
  hu: {
    home: 'Főoldal',
    dashboard: 'Irányítópult',
    researchPapers: 'Kutatási cikkek',
    knowledgeGraph: 'Tudásgráf',
    aiInsights: 'AI betekintések',
    welcomeToNASA: 'Üdvözöljük a NASA BioExplorer-ben',
    exploreFuture: 'Fedezze fel az űrbiológia jövőjét AI-alapú betekintésekkel és interaktív vizualizációkkal',
    researchPapersCount: 'Kutatási cikkek',
    researchAreasCount: 'Kutatási területek',
    organizationsCount: 'Szervezetek',
    totalPapers: 'Összes cikk',
    totalAreas: 'Összes terület',
    totalOrganizations: 'Összes szervezet',
    researchTimeline: 'Kutatási idővonal',
    mostVisitedPapers: 'Leglátogatottabb cikkek',
    systemStatus: 'Rendszerállapot',
    weather: 'Időjárás',
    online: 'Online',
    offline: 'Offline',
    allPapers: 'Összes cikk',
    summary: 'Összefoglaló',
    knowledgeGraphBtn: 'Tudásgráf',
    keywords: 'Kulcsszavak',
    openPaper: 'Cikk megnyitása',
    sortBy: 'Rendezés',
    filterBy: 'Szűrés',
    loading: 'Betöltés...',
    search: 'Keresés',
    filter: 'Szűrő',
    view: 'Nézet',
    grid: 'Rács',
    list: 'Lista',
    selectAll: 'Összes kiválasztása',
    deselectAll: 'Kiválasztás megszüntetése',
    export: 'Exportálás',
    previous: 'Előző',
    next: 'Következő',
    page: 'Oldal',
    of: '/',
    noResults: 'Nincs találat',
    tryAdjusting: 'Próbálja megállítani a keresést vagy szűrőket'
  },
  ru: {
    home: 'Главная',
    dashboard: 'Панель управления',
    researchPapers: 'Исследовательские статьи',
    knowledgeGraph: 'Граф знаний',
    aiInsights: 'AI аналитика',
    welcomeToNASA: 'Добро пожаловать в NASA BioExplorer',
    exploreFuture: 'Исследуйте будущее космической биологии с помощью AI-аналитики и интерактивных визуализаций',
    researchPapersCount: 'Исследовательские статьи',
    researchAreasCount: 'Области исследований',
    organizationsCount: 'Организации',
    totalPapers: 'Всего статей',
    totalAreas: 'Всего областей',
    totalOrganizations: 'Всего организаций',
    researchTimeline: 'Временная шкала исследований',
    mostVisitedPapers: 'Самые посещаемые статьи',
    systemStatus: 'Статус системы',
    weather: 'Погода',
    online: 'Онлайн',
    offline: 'Офлайн',
    allPapers: 'Все статьи',
    summary: 'Резюме',
    knowledgeGraphBtn: 'Граф знаний',
    keywords: 'Ключевые слова',
    openPaper: 'Открыть статью',
    sortBy: 'Сортировать по',
    filterBy: 'Фильтровать по',
    loading: 'Загрузка...',
    search: 'Поиск',
    filter: 'Фильтр',
    view: 'Вид',
    grid: 'Сетка',
    list: 'Список',
    selectAll: 'Выбрать все',
    deselectAll: 'Снять выбор',
    export: 'Экспорт',
    previous: 'Предыдущий',
    next: 'Следующий',
    page: 'Страница',
    of: 'из',
    noResults: 'Результаты не найдены',
    tryAdjusting: 'Попробуйте изменить поиск или фильтры'
  },
  ja: {
    home: 'ホーム',
    dashboard: 'ダッシュボード',
    researchPapers: '研究論文',
    knowledgeGraph: '知識グラフ',
    aiInsights: 'AIインサイト',
    welcomeToNASA: 'NASA BioExplorerへようこそ',
    exploreFuture: 'AI駆動のインサイトとインタラクティブな可視化で宇宙生物学の未来を探求',
    researchPapersCount: '研究論文',
    researchAreasCount: '研究分野',
    organizationsCount: '組織',
    totalPapers: '総論文数',
    totalAreas: '総分野数',
    totalOrganizations: '総組織数',
    researchTimeline: '研究タイムライン',
    mostVisitedPapers: '最も訪問された論文',
    systemStatus: 'システム状態',
    weather: '天気',
    online: 'オンライン',
    offline: 'オフライン',
    allPapers: 'すべての論文',
    summary: '要約',
    knowledgeGraphBtn: '知識グラフ',
    keywords: 'キーワード',
    openPaper: '論文を開く',
    sortBy: '並び順',
    filterBy: 'フィルター',
    loading: '読み込み中...',
    search: '検索',
    filter: 'フィルター',
    view: '表示',
    grid: 'グリッド',
    list: 'リスト',
    selectAll: 'すべて選択',
    deselectAll: 'すべて解除',
    export: 'エクスポート',
    previous: '前へ',
    next: '次へ',
    page: 'ページ',
    of: '/',
    noResults: '結果が見つかりません',
    tryAdjusting: '検索条件やフィルターを調整してください'
  },
  ko: {
    home: '홈',
    dashboard: '대시보드',
    researchPapers: '연구 논문',
    knowledgeGraph: '지식 그래프',
    aiInsights: 'AI 인사이트',
    welcomeToNASA: 'NASA BioExplorer에 오신 것을 환영합니다',
    exploreFuture: 'AI 기반 인사이트와 인터랙티브 시각화로 우주 생물학의 미래를 탐구하세요',
    researchPapersCount: '연구 논문',
    researchAreasCount: '연구 분야',
    organizationsCount: '조직',
    totalPapers: '총 논문 수',
    totalAreas: '총 분야 수',
    totalOrganizations: '총 조직 수',
    researchTimeline: '연구 타임라인',
    mostVisitedPapers: '가장 많이 방문한 논문',
    systemStatus: '시스템 상태',
    weather: '날씨',
    online: '온라인',
    offline: '오프라인',
    allPapers: '모든 논문',
    summary: '요약',
    knowledgeGraphBtn: '지식 그래프',
    keywords: '키워드',
    openPaper: '논문 열기',
    sortBy: '정렬 기준',
    filterBy: '필터 기준',
    loading: '로딩 중...',
    search: '검색',
    filter: '필터',
    view: '보기',
    grid: '그리드',
    list: '목록',
    selectAll: '모두 선택',
    deselectAll: '선택 해제',
    export: '내보내기',
    previous: '이전',
    next: '다음',
    page: '페이지',
    of: '/',
    noResults: '결과를 찾을 수 없습니다',
    tryAdjusting: '검색 조건이나 필터를 조정해보세요'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('nasa-bioexplorer-language');
    if (savedLanguage && languages[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (languageCode) => {
    if (languages[languageCode]) {
      setIsLoading(true);
      setCurrentLanguage(languageCode);
      localStorage.setItem('nasa-bioexplorer-language', languageCode);
      setTimeout(() => setIsLoading(false), 300);
    }
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    languages,
    changeLanguage,
    t,
    isLoading
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
